Repository webb-tools/webb.js, pull requests merged in 2022-09, with the labels that each got.

#275 chore: fix docs
  .github/workflows/pr-any.yml
  package.json
  packages/types/src/interfaces/types-lookup.ts
  tests/integration_tests/substrate/vanchorTests.spec.ts
  yarn.lock
Labels: needs review 👓

#280 Fix versions packages versions
  package.json
  packages/api-derive/package.json
  packages/api/package.json
  packages/app-util/package.json
  packages/sdk-core/package.json
  packages/test-utils/package.json
  packages/types/package.json
  packages/wasm-utils/package.json
  yarn.lock
Labels: dependencies

#288 Update UTXO and Keypair state management
  package.json
  packages/sdk-core/src/__test__/arkworks-proving.spec.ts
  packages/sdk-core/src/__test__/keypair.spec.ts
  packages/sdk-core/src/__test__/serialization-integrations/utxo-and-keypair.spec.ts
  packages/sdk-core/src/__test__/utils.ts
  packages/sdk-core/src/__test__/utxo.spec.ts
  packages/sdk-core/src/keypair.ts
  packages/sdk-core/src/proving/circom/proving-manager-thread.ts
  packages/sdk-core/src/solidity-utils/circom-utxo.ts
  packages/sdk-core/src/solidity-utils/variable-anchor.ts
  packages/sdk-core/src/utxo.ts
  packages/wasm-utils/src/note/mod.rs
  yarn.lock
Labels: needs review 👓

#283 Introduce Vanchor Transaction for the Evm and Test Account Setup via the test-utils package
  packages/test-utils/package.json
  packages/test-utils/src/accountSetup.ts
  packages/test-utils/src/localEvmChain.ts
  packages/test-utils/src/localTestnet.ts
Labels: needs changes 🔧

#278 Introduce running of protocol substrate node and dkg node via the test-utils package
  package.json
  packages/api/package.json
  packages/api/src/index.ts
  packages/test-utils/package.json
  packages/test-utils/src/index.ts
  packages/test-utils/src/substrate/localDkg.ts
  packages/test-utils/src/substrate/localProtocolSubstrate.ts
  packages/test-utils/src/substrate/substrateNodeBase.ts
  scripts/init-vanchor-pool-share.ts
  tests/integration_tests/substrate/mixerTests.spec.ts
  tests/integration_tests/substrate/vanchorTests.spec.ts
  tests/integration_tests/substrate/wrapUnwrap.spec.ts
  tests/utils/backend-utils.ts
  tests/utils/substrate-utils.ts
  yarn.lock
Labels: needs changes 🔧
