Repository webb-tools/webb.js, pull requests merged in 2022-08, with the labels that each got.

#257 Adding wrap/unwrap integration tests for substrate side
  tests/integration_tests/substrate/wrapUnwrap.spec.ts
Labels: needs review 👓

#263 Update ganache version
  package.json
  packages/test-utils/package.json
  yarn.lock
Labels: needs changes 🔧

#262 Added vanchor poolshare script
  package.json
  packages/types/scripts/updateMetadata.ts
  packages/types/src/interfaces/augment-api-consts.ts
  packages/types/src/interfaces/augment-api-errors.ts
  packages/types/src/interfaces/augment-api-events.ts
  packages/types/src/interfaces/augment-api-query.ts
  packages/types/src/interfaces/augment-api-runtime.ts
  packages/types/src/interfaces/augment-api-tx.ts
  packages/types/src/interfaces/lookup.ts
  packages/types/src/interfaces/registry.ts
  packages/types/src/interfaces/types-lookup.ts
  packages/types/src/metadata/metadata.json
  packages/types/src/metadata/static-latest.ts
  scripts/init-vanchor-pool-share.ts
  tests/integration_tests/substrate/wrapUnwrap.spec.ts
Labels: needs changes 🔧

#269 Move LocalEvmChain to test-utils
  examples/node/substrate/mixer.ts
  package.json
  packages/api-derive/__test__/merkleTreeBn254.spec.ts
  packages/api-derive/package.json
  packages/api/package.json
  packages/sdk-core/package.json
  packages/sdk-core/src/__test__/proposals.spec.ts
  packages/sdk-core/src/proposals/ProposalHeader.ts
  packages/sdk-core/src/proposals/ProposalKinds.ts
  packages/test-utils/package.json
  packages/test-utils/src/index.ts
  packages/test-utils/src/localEvmChain.ts
  packages/test-utils/src/utils.ts
  packages/types/package.json
  packages/types/src/interfaces/augment-api-consts.ts
  packages/types/src/interfaces/augment-api-errors.ts
  packages/types/src/interfaces/augment-api-events.ts
  packages/types/src/interfaces/augment-api-query.ts
  packages/types/src/interfaces/augment-api-runtime.ts
  packages/types/src/interfaces/augment-api-tx.ts
  packages/types/src/interfaces/augment-types.ts
  packages/types/src/interfaces/lookup.ts
  packages/types/src/interfaces/registry.ts
  packages/types/src/interfaces/types-lookup.ts
  packages/types/src/metadata/metadata.json
  packages/types/src/metadata/static-latest.ts
  scripts/webb-build-dev.cjs
  yarn.lock
Labels: needs review 👓

#273 Remove Unnecessary Chai Dependency
  packages/sdk-core/src/proposals/ProposalHeader.ts
  packages/test-utils/src/localEvmChain.ts
Labels: approved ✅
